/**
 * Each new term in the Fibonacci sequence is generated by adding
 * the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 * fibonacci(num-1) + fibonacci(num - 2);
 */

 function mf(index, cache = []) {
   if (cache[index]) {
      return cache[index] 
   }
   else {
      if (index < 3) return 1
      else {
         cache[index] = mf(index - 1, cache) + mf(index - 2, cache)
      }
   }
   return cache[index];
}
console.log(mf(33))
